project_id = "fwdtjszxnnfqxjevlasm"

[functions.check-contract-expiry]
verify_jwt = false

[functions.send-late-notification]
verify_jwt = false

[functions.send-daily-summary]
verify_jwt = false

[functions.ai-document-reader]
verify_jwt = false

[functions.send-document-expiry-notification]
verify_jwt = false

[functions.create-employee-account]
verify_jwt = false

[functions.webauthn-register-options]
verify_jwt = false

[functions.webauthn-register-verify]
verify_jwt = false

[functions.webauthn-auth-options]
verify_jwt = false

[functions.webauthn-auth-verify]
verify_jwt = false
